import React,{useEffect,useMemo,useState} from 'react';
import {createRoot} from 'react-dom/client';
import {createClient} from '@supabase/supabase-js';
import {CalendarDays,Users,Clock3,Plus,ChevronLeft,ChevronRight,LogOut,Settings,CheckCircle2,AlertCircle,Trash2,Edit3,Menu,X,Building2,UserRound,Copy,Download} from 'lucide-react';
import './styles.css';

const SUPABASE_URL=import.meta.env.VITE_SUPABASE_URL;
const SUPABASE_ANON_KEY=import.meta.env.VITE_SUPABASE_ANON_KEY;
const supabase=SUPABASE_URL&&SUPABASE_ANON_KEY?createClient(SUPABASE_URL,SUPABASE_ANON_KEY):null;
const demoKey='elara_demo_v1';
const seed={business:{name:'Acme Coffee Co.',timezone:'America/New_York'},employees:[
{id:'e1',name:'Alex Morgan',role:'Barista',email:'alex@example.com',color:'#2563eb',availability:'Mon–Fri'},
{id:'e2',name:'Jordan Lee',role:'Shift Lead',email:'jordan@example.com',color:'#7c3aed',availability:'Tue–Sat'},
{id:'e3',name:'Sam Patel',role:'Barista',email:'sam@example.com',color:'#059669',availability:'Mon–Sun'},
{id:'e4',name:'Taylor Kim',role:'Cashier',email:'taylor@example.com',color:'#ea580c',availability:'Wed–Sun'}],
shifts:[
{id:'s1',employee_id:'e1',date:'2026-08-17',start:'08:00',end:'14:00',role:'Barista',location:'Main St'},
{id:'s2',employee_id:'e2',date:'2026-08-17',start:'12:00',end:'20:00',role:'Shift Lead',location:'Main St'},
{id:'s3',employee_id:'e3',date:'2026-08-18',start:'09:00',end:'15:00',role:'Barista',location:'Main St'},
{id:'s4',employee_id:'e4',date:'2026-08-18',start:'14:00',end:'20:00',role:'Cashier',location:'Main St'},
{id:'s5',employee_id:'e1',date:'2026-08-19',start:'08:00',end:'14:00',role:'Barista',location:'Main St'},
{id:'s6',employee_id:'e3',date:'2026-08-19',start:'14:00',end:'20:00',role:'Barista',location:'Main St'},
{id:'s7',employee_id:'e2',date:'2026-08-20',start:'08:00',end:'16:00',role:'Shift Lead',location:'Main St'},
{id:'s8',employee_id:'e4',date:'2026-08-20',start:'12:00',end:'18:00',role:'Cashier',location:'Main St'}]};
function loadDemo(){try{return JSON.parse(localStorage.getItem(demoKey))||seed}catch{return seed}}
function saveDemo(d){localStorage.setItem(demoKey,JSON.stringify(d))}
const fmtDate=d=>new Intl.DateTimeFormat('en-US',{weekday:'short',month:'short',day:'numeric'}).format(new Date(d+'T12:00:00'));
const weekStart=(d)=>{let x=new Date(d+'T12:00:00');let day=x.getDay();x.setDate(x.getDate()-(day===0?6:day-1));return x.toISOString().slice(0,10)};
const addDays=(d,n)=>{let x=new Date(d+'T12:00:00');x.setDate(x.getDate()+n);return x.toISOString().slice(0,10)};
const hours=(a,b)=>{let [ah,am]=a.split(':').map(Number),[bh,bm]=b.split(':').map(Number);return (bh*60+bm-ah*60-am)/60};

function App(){
 const [session,setSession]=useState(null); const [mode,setMode]=useState(supabase?'login':'demo'); const [data,setData]=useState(loadDemo); const [view,setView]=useState('schedule'); const [week,setWeek]=useState(weekStart('2026-08-17')); const [modal,setModal]=useState(null); const [mobile,setMobile]=useState(false); const [toast,setToast]=useState('');
 useEffect(()=>{if(!supabase)return;supabase.auth.getSession().then(({data})=>setSession(data.session));const {data:sub}=supabase.auth.onAuthStateChange((_e,s)=>setSession(s));return()=>sub.subscription.unsubscribe()},[]);
 useEffect(()=>{if(toast){let t=setTimeout(()=>setToast(''),2500);return()=>clearTimeout(t)}},[toast]);
 const employees=data.employees; const shifts=data.shifts;
 function update(next){setData(next);saveDemo(next);setToast('Saved');}
 function addShift(f){update({...data,shifts:[...shifts,{...f,id:'s'+Date.now()}]});setModal(null)}
 function deleteShift(id){update({...data,shifts:shifts.filter(s=>s.id!==id)});setModal(null)}
 function addEmployee(f){update({...data,employees:[...employees,{...f,id:'e'+Date.now(),color:'#475569'}]});setModal(null)}
 function exportCsv(){let csv='Employee,Date,Start,End,Role,Location,Hours\n'+shifts.map(s=>{let e=employees.find(x=>x.id===s.employee_id);return [e?.name,s.date,s.start,s.end,s.role,s.location,hours(s.start,s.end)].join(',')}).join('\n');let a=document.createElement('a');a.href=URL.createObjectURL(new Blob([csv],{type:'text/csv'}));a.download='schedule.csv';a.click()}
 if(mode==='login'&&!session) return <Login onDemo={()=>setMode('demo')}/>;
 return <div className="app"><header className="top"><button className="icon mobileOnly" onClick={()=>setMobile(!mobile)}>{mobile?<X/>:<Menu/>}</button><div className="brand"><div className="logo"><CalendarDays size={19}/></div><span>Elara</span></div><div className="topRight"><span className="business"><Building2 size={16}/>{data.business.name}</span><button className="avatar">OW</button></div></header>
 <div className="body"><aside className={mobile?'side open':'side'}><nav>{[['schedule',CalendarDays,'Schedule'],['employees',Users,'Employees'],['settings',Settings,'Settings']].map(([id,I,label])=><button key={id} className={view===id?'nav active':'nav'} onClick={()=>{setView(id);setMobile(false)}}><I size={18}/>{label}</button>)}</nav><div className="sideBottom"><div className="upgrade"><b>Pro scheduling</b><span>Auto-fill, time-off and labor insights.</span><button onClick={()=>setToast('Pro features can be enabled with your Supabase account.')}>Explore</button></div><button className="nav" onClick={()=>{if(supabase) supabase.auth.signOut();setMode('login')}}><LogOut size={18}/>Sign out</button></div></aside>
 <main className="main">{view==='schedule'?<Schedule data={data} week={week} setWeek={setWeek} setModal={setModal} exportCsv={exportCsv}/>:view==='employees'?<Employees data={data} setModal={setModal}/>:<SettingsPage data={data} update={update}/>}</main></div>
 {modal?.type==='shift'&&<ShiftModal employees={employees} initial={modal.shift} onClose={()=>setModal(null)} onSave={addShift} onDelete={deleteShift}/>} {modal?.type==='employee'&&<EmployeeModal onClose={()=>setModal(null)} onSave={addEmployee}/>} {toast&&<div className="toast">{toast}</div>}</div>
}
function Login({onDemo}){const [email,setEmail]=useState('');const [password,setPassword]=useState('');const [err,setErr]=useState('');async function login(e){e.preventDefault();if(!supabase)return onDemo();let r=await supabase.auth.signInWithPassword({email,password});if(r.error)setErr(r.error.message)}return <div className="login"><div className="loginCard"><div className="brand big"><div className="logo"><CalendarDays/></div><span>Elara</span></div><h1>Run your team without the spreadsheet.</h1><p>Schedule shifts, manage employees and keep everyone aligned.</p><form onSubmit={login}><label>Email<input value={email} onChange={e=>setEmail(e.target.value)} type="email" required placeholder="owner@company.com"/></label><label>Password<input value={password} onChange={e=>setPassword(e.target.value)} type="password" required placeholder="••••••••"/></label>{err&&<div className="error"><AlertCircle size={16}/>{err}</div>}<button className="primary full">Sign in</button></form><div className="or">or</div><button className="secondary full" onClick={onDemo}>Try the demo</button><small>Production mode uses Supabase Auth + Postgres. Demo mode is local-only.</small></div></div>}
function Schedule({data,week,setWeek,setModal,exportCsv}){let days=Array.from({length:7},(_,i)=>addDays(week,i));let weekShifts=data.shifts.filter(s=>s.date>=week&&s.date<addDays(week,7));let total=weekShifts.reduce((a,s)=>a+hours(s.start,s.end),0);return <><div className="pageHead"><div><h1>Weekly schedule</h1><p>{fmtDate(week)} – {fmtDate(addDays(week,6))}</p></div><div className="actions"><button className="secondary" onClick={exportCsv}><Download size={16}/>Export</button><button className="primary" onClick={()=>setModal({type:'shift'})}><Plus size={17}/>Add shift</button></div></div><div className="metrics"><div><span>Total scheduled</span><b>{total.toFixed(1)} hrs</b></div><div><span>Team members</span><b>{data.employees.length}</b></div><div><span>Open shifts</span><b>0</b></div><div><span>Coverage</span><b className="good">100%</b></div></div><div className="toolbar"><button className="secondary small" onClick={()=>setWeek(addDays(week,-7))}><ChevronLeft/></button><button className="secondary small" onClick={()=>setWeek(weekStart(new Date().toISOString().slice(0,10)))}>Today</button><button className="secondary small" onClick={()=>setWeek(addDays(week,7))}><ChevronRight/></button></div><div className="scheduleWrap"><div className="scheduleGrid"><div className="corner">Team</div>{days.map(d=><div className="dayHead" key={d}><b>{new Date(d+'T12:00:00').toLocaleDateString('en-US',{weekday:'short'})}</b><span>{new Date(d+'T12:00:00').getDate()}</span></div>)}{data.employees.map(e=><React.Fragment key={e.id}><div className="employeeCell"><div className="empDot" style={{background:e.color}}></div><div><b>{e.name}</b><span>{e.role}</span></div></div>{days.map(d=>{let ss=weekShifts.filter(s=>s.employee_id===e.id&&s.date===d);return <div className="shiftCell" key={d} onClick={()=>ss.length?setModal({type:'shift',shift:ss[0]}):setModal({type:'shift',prefill:{employee_id:e.id,date:d}})}>{ss.map(s=><div className="shift" key={s.id}><b>{s.start}–{s.end}</b><span>{s.role}</span><small>{s.location}</small></div>)}{!ss.length&&<span className="addHint">+ Add</span>}</div>})}</React.Fragment>)}</div></div></>}
function Employees({data,setModal}){return <><div className="pageHead"><div><h1>Employees</h1><p>Manage your team and scheduling preferences.</p></div><button className="primary" onClick={()=>setModal({type:'employee'})}><Plus size={17}/>Add employee</button></div><div className="employeeCards">{data.employees.map(e=><div className="employeeCard" key={e.id}><div className="person"><div className="avatar bigAvatar" style={{background:e.color}}>{e.name.split(' ').map(x=>x[0]).join('')}</div><div><h3>{e.name}</h3><p>{e.role}</p></div></div><div className="info"><span><UserRound size={15}/>{e.email}</span><span><Clock3 size={15}/>{e.availability}</span></div><button className="secondary small" onClick={()=>setModal({type:'shift',prefill:{employee_id:e.id,date:new Date().toISOString().slice(0,10)}})}><Plus size={15}/>Schedule shift</button></div>)}</div></>}
function SettingsPage({data,update}){const [name,setName]=useState(data.business.name);const [tz,setTz]=useState(data.business.timezone);return <><div className="pageHead"><div><h1>Settings</h1><p>Business defaults and scheduling preferences.</p></div></div><div className="settingsCard"><h2>Business profile</h2><label>Business name<input value={name} onChange={e=>setName(e.target.value)}/></label><label>Time zone<select value={tz} onChange={e=>setTz(e.target.value)}><option>America/New_York</option><option>America/Chicago</option><option>America/Denver</option><option>America/Los_Angeles</option></select></label><button className="primary" onClick={()=>update({...data,business:{name,timezone:tz}})}>Save changes</button></div></>}
function ShiftModal({employees,initial,prefill,onClose,onSave,onDelete}){const x=initial||prefill||{};const [f,setF]=useState({employee_id:x.employee_id||employees[0]?.id,date:x.date||new Date().toISOString().slice(0,10),start:x.start||'09:00',end:x.end||'17:00',role:x.role||employees.find(e=>e.id===x.employee_id)?.role||'Barista',location:x.location||'Main St'});return <div className="overlay"><div className="modal"><div className="modalHead"><h2>{initial?'Edit shift':'Add shift'}</h2><button className="icon" onClick={onClose}><X/></button></div><label>Employee<select value={f.employee_id} onChange={e=>setF({...f,employee_id:e.target.value})}>{employees.map(e=><option value={e.id} key={e.id}>{e.name}</option>)}</select></label><div className="two"><label>Date<input type="date" value={f.date} onChange={e=>setF({...f,date:e.target.value})}/></label><label>Role<input value={f.role} onChange={e=>setF({...f,role:e.target.value})}/></label></div><div className="two"><label>Start<input type="time" value={f.start} onChange={e=>setF({...f,start:e.target.value})}/></label><label>End<input type="time" value={f.end} onChange={e=>setF({...f,end:e.target.value})}/></label></div><label>Location<input value={f.location} onChange={e=>setF({...f,location:e.target.value})}/></label><div className="modalActions">{initial&&<button className="danger" onClick={()=>onDelete(initial.id)}><Trash2 size={16}/>Delete</button>}<span></span><button className="secondary" onClick={onClose}>Cancel</button><button className="primary" onClick={()=>onSave(f)}><CheckCircle2 size={16}/>Save shift</button></div></div></div>}
function EmployeeModal({onClose,onSave}){const [f,setF]=useState({name:'',role:'Barista',email:'',availability:'Mon–Sun'});return <div className="overlay"><div className="modal"><div className="modalHead"><h2>Add employee</h2><button className="icon" onClick={onClose}><X/></button></div><label>Full name<input autoFocus value={f.name} onChange={e=>setF({...f,name:e.target.value})} placeholder="Jamie Smith"/></label><label>Email<input type="email" value={f.email} onChange={e=>setF({...f,email:e.target.value})} placeholder="jamie@company.com"/></label><label>Role<input value={f.role} onChange={e=>setF({...f,role:e.target.value})}/></label><label>Availability<input value={f.availability} onChange={e=>setF({...f,availability:e.target.value})}/></label><div className="modalActions"><span></span><button className="secondary" onClick={onClose}>Cancel</button><button className="primary" disabled={!f.name} onClick={()=>onSave(f)}>Add employee</button></div></div></div>}

createRoot(document.getElementById('root')).render(<App/>);
